### ISSUE TITLE
パンくずリスト

### ISSUE THREAD

**Issue by takejohn** [TeamSekai/Sekai.CDN#17]
1つ上のディレクトリだけでなくルートのディレクトリなど任意の祖先ディレクトリを移動できるようにパンくずリスト的なものを実装したい

**Comment by AlizqQwQ** [comment]
パンくずってなに...? 
義務教育の敗北でたな

**Comment by ringo360** [comment]
https://ggrks.ringoxd.dev/パンくずリスト

**Comment by AlizqQwQ** [comment]
義務教育関係ないねこれ
